node('master'){
    
notify('Project Build Started')

try{

stage('git checkout') {
git 'https://github.com/amitvashist7/jenkins2-course-spring-boot.git'
}    
    

def project_path="spring-boot-samples/spring-boot-sample-atmosphere"

dir(project_path) {

stage('Build & Compile') {    
sh 'mvn clean package'
}
stage('Archive Packages' ) {
archiveArtifacts 'target/*.jar'
}

stage('Deploy Code to Stage Env.'){
sh 'docker-compose up -d --build'
}

notify('Project Build Completed')
}

}catch(err) {
notify("Error ${err}")
currentBuild.result='FAILURE'
}

}
def notify(status){
    emailext(
        to: "amitvashist7@gmail.com",
        subject: "${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
        body: """<p>${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' :</p>
        <p>Check console output at <a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a></p>""",
        
        )
}
